#ifndef __INCLUDE_NEFKO_PRIV_TAGS_H__
#define __INCLUDE_NEFKO_PRIV_TAGS_H__

#define TIFF_TAG_NEWSUBFILETYPE     254
#define TIFF_TAG_IMAGEWIDTH         256
#define TIFF_TAG_IMAGELENGTH        257
#define TIFF_TAG_BITSPERSAMPLE      258
#define TIFF_TAG_COMPRESSION        259
#define   TIFF_COMPRESSION_NONE       1
#define   TIFF_COMPRESSION_NIKON      32803
#define TIFF_TAG_PHOTOMETRICINTERP  262
#define TIFF_TAG_SAMPLESPERPIXEL    277
#define TIFF_TAG_SAMPLEFORMAT       339

#define TIFF_TAG_STRIPOFFSETS       273
#define TIFF_TAG_ROWSPERSTRIP       278
#define TIFF_TAG_STRIPBYTECOUNTS    279

#define TIFF_TAG_MAKER              271
#define TIFF_TAG_MODEL              272
#define TIFF_TAG_SUBIFDS            330
#define TIFF_TAG_EXIFIFD            34665

#define TIFF_TAG_EXIF_MAKERNOTE     37500

#define TIFF_TAG_MAKERNOTE_SERIAL     29
#define TIFF_TAG_MAKERNOTE_SHUTTER    167

#define TIFF_TAG_MAKERNOTE_IMAGE_SETTINGS  151
/* Header v.0205 has a special offset */
#define NEF_IMAGE_SETTINGS_0205_OFF         4
#define NEF_IMAGE_SETTINGS_OFF         284


#endif /* __INCLUDE_NEFKO_PRIV_TAGS_H__ */

